export const CLEANING_TASKS = [
  {
    id: '1',
    room: '101',
    category: 'Standard',
    description: 'Full cleaning including bathroom',
    dueDate: '2023-06-15T10:00:00',
    priority: 'High',
    status: 'inspected',
    createDate: '2023-06-10T08:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm1',
        type: 'maintenance',
        description: 'Bathroom faucet leaking',
        priority: 'High',
      },
      {
        id: 'd1',
        type: 'damage',
        description: 'Crack in wall tile',
        priority: 'Medium',
      },
    ],
  },
  {
    id: '2',
    room: '202',
    category: 'Deluxe',
    description: 'Change bed sheets and towels',
    dueDate: '2023-06-15T12:00:00',
    priority: 'Medium',
    status: 'inspected',
    createDate: '2023-06-10T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd2',
        type: 'damage',
        description: 'Headboard scratched',
        priority: 'Low',
      },
    ],
  },
  {
    id: '3',
    room: '305',
    category: 'Suite',
    description: 'Deep cleaning after checkout',
    dueDate: '2023-06-14T14:00:00',
    priority: 'High',
    status: 'cleaned',
    createDate: '2023-06-09T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm3',
        type: 'maintenance',
        description: 'AC not cooling',
        priority: 'High',
      },
      {
        id: 'd3',
        type: 'damage',
        description: 'Mirror cracked',
        priority: 'Medium',
      },
    ],
  },
  {
    id: '4',
    room: '107',
    category: 'Standard',
    description: 'Quick refresh between guests',
    dueDate: '2023-06-16T09:00:00',
    priority: 'Low',
    status: 'dirty',
    createDate: '2023-06-11T08:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '5',
    room: '210',
    category: 'Deluxe',
    description: 'VIP guest preparation',
    dueDate: '2023-06-13T16:00:00',
    priority: 'High',
    status: 'cleaned',
    createDate: '2023-06-08T11:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm5',
        type: 'maintenance',
        description: 'TV remote not working',
        priority: 'Low',
      },
    ],
  },
  {
    id: '6',
    room: '115',
    category: 'Standard',
    description: 'Regular daily cleaning',
    dueDate: '2023-06-15T11:00:00',
    priority: 'Medium',
    status: 'inspected',
    createDate: '2023-06-10T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '7',
    room: '301',
    category: 'Suite',
    description: 'Special request: extra towels',
    dueDate: '2023-06-14T13:00:00',
    priority: 'Medium',
    status: 'cleaned',
    createDate: '2023-06-09T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd7',
        type: 'damage',
        description: 'Broken wardrobe door',
        priority: 'High',
      },
    ],
  },
  {
    id: '8',
    room: '204',
    category: 'Deluxe',
    description: 'Full cleaning with carpet shampoo',
    dueDate: '2023-06-16T15:00:00',
    priority: 'High',
    status: 'inspected',
    createDate: '2023-06-11T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm8',
        type: 'maintenance',
        description: 'Clogged shower drain',
        priority: 'Medium',
      },
    ],
  },
  {
    id: '9',
    room: '102',
    category: 'Standard',
    description: 'Checkout cleaning',
    dueDate: '2023-06-14T10:00:00',
    priority: 'Medium',
    status: 'cleaned',
    createDate: '2023-06-09T08:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '10',
    room: '208',
    category: 'Deluxe',
    description: 'Prepare for long-term guest',
    dueDate: '2023-06-15T14:00:00',
    priority: 'High',
    status: 'inspected',
    createDate: '2023-06-10T12:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd10',
        type: 'damage',
        description: 'Window curtain torn',
        priority: 'Medium',
      },
    ],
  },
  {
    id: '11',
    room: '303',
    category: 'Suite',
    description: 'Full service with minibar restock',
    dueDate: '2023-06-16T11:00:00',
    priority: 'High',
    status: 'inspected',
    createDate: '2023-06-11T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '12',
    room: '110',
    category: 'Standard',
    description: 'Quick tidy up',
    dueDate: '2023-06-15T09:00:00',
    priority: 'Low',
    status: 'cleaned',
    createDate: '2023-06-10T07:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm12',
        type: 'maintenance',
        description: 'Light bulb flickering',
        priority: 'Low',
      },
    ],
  },
  {
    id: '13',
    room: '118',
    category: 'Standard',
    description: 'Strong odor and stained bedsheet',
    dueDate: '2023-06-17T10:30:00',
    priority: 'High',
    status: 'dirty',
    createDate: '2023-06-12T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd13',
        type: 'damage',
        description: 'Carpet heavily stained',
        status: 'open',
      },
    ],
  },
  {
    id: '14',
    room: '220',
    category: 'Deluxe',
    description: 'Overflowed toilet and trash full',
    dueDate: '2023-06-17T14:00:00',
    priority: 'High',
    status: 'dirty',
    createDate: '2023-06-12T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm14',
        type: 'maintenance',
        description: 'Toilet plumbing issue',
        status: 'open',
      },
    ],
  },
  {
    id: '15',
    room: '119',
    category: 'Standard',
    description: 'Bathroom mold and dirty mirror',
    dueDate: '2023-06-17T12:00:00',
    priority: 'Medium',
    status: 'dirty',
    createDate: '2023-06-12T11:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd15',
        type: 'damage',
        description: 'Mirror cracked and loose',
        status: 'in-progress',
      },
      {
        id: 'm15',
        type: 'maintenance',
        description: 'Ventilation fan not working',
        status: 'open',
      },
    ],
  },
  {
    id: '16',
    room: '309',
    category: 'Suite',
    description: 'Spilled wine on couch and rug',
    dueDate: '2023-06-18T09:00:00',
    priority: 'High',
    status: 'dirty',
    createDate: '2023-06-12T12:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd16',
        type: 'damage',
        description: 'Wine stain on upholstery',
        status: 'open',
      },
    ],
  },
  {
    id: '17',
    room: '215',
    category: 'Deluxe',
    description: 'Overflowing trash bin and dusty surfaces',
    dueDate: '2023-06-18T11:00:00',
    priority: 'Medium',
    status: 'dirty',
    createDate: '2023-06-12T13:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
];
