// item-requests.js

export const CLEANING_TASKS = [
  {
    id: '1',
    itemName: 'Bath Towels',
    requestDate: '2024-12-22',
    quantity: 50,
    status: 'Approved',
  },
  {
    id: '2',
    itemName: 'Shampoo Bottles',
    requestDate: '2024-12-21',
    quantity: 200,
    status: 'Requested',
  },
  {
    id: '3',
    itemName: 'Light Bulbs',
    requestDate: '2024-12-20',
    quantity: 30,
    status: 'Rejected',
  },
  {
    id: '4',
    itemName: 'Coffee Pods',
    requestDate: '2024-12-19',
    quantity: 150,
    status: 'Received',
  },
  {
    id: '5',
    itemName: 'Toilet Paper Rolls',
    requestDate: '2024-12-18',
    quantity: 100,
    status: 'Requested',
  },
  {
    id: '6',
    itemName: 'Room Slippers',
    requestDate: '2024-12-17',
    quantity: 75,
    status: 'Approved',
  },
  {
    id: '7',
    itemName: 'Water Bottles',
    requestDate: '2024-12-16',
    quantity: 300,
    status: 'Received',
  },
  {
    id: '8',
    itemName: 'Laundry Bags',
    requestDate: '2024-12-15',
    quantity: 40,
    status: 'Rejected',
  },
  {
    id: '9',
    itemName: 'Cleaning Sprays',
    requestDate: '2024-12-14',
    quantity: 80,
    status: 'Approved',
  },
  {
    id: '10',
    itemName: 'Paper Towels',
    requestDate: '2024-12-13',
    quantity: 120,
    status: 'Requested',
  },
  {
    id: '11',
    itemName: 'Trash Bags',
    requestDate: '2024-12-12',
    quantity: 200,
    status: 'Received',
  },
  {
    id: '12',
    itemName: 'Hand Soap Dispensers',
    requestDate: '2024-12-11',
    quantity: 25,
    status: 'Rejected',
  },
  {
    id: '13',
    itemName: 'Mop Heads',
    requestDate: '2024-12-10',
    quantity: 15,
    status: 'Approved',
  },
  {
    id: '14',
    itemName: 'Dish Soap',
    requestDate: '2024-12-09',
    quantity: 60,
    status: 'Requested',
  },
  {
    id: '15',
    itemName: 'Vacuum Filters',
    requestDate: '2024-12-08',
    quantity: 10,
    status: 'Received',
  },
  {
    id: '16',
    itemName: 'Gloves (Cleaning)',
    requestDate: '2024-12-07',
    quantity: 100,
    status: 'Approved',
  },
];
