export const scheduleData = [
  {
    date: 'Monday, Oct 23',
    workingHours: '8:00 AM – 4:00 PM',
    breakTime: '12:00 PM – 12:30 PM',
    tasks: [
      {
        id: 1,
        room: '3',
        task: 'Deep Cleaning',
        category: 'Single',
        priority: 'High',
        status: 'Cleaned',
      },
      {
        id: 2,
        room: '7',
        task: 'Standard Cleaning',
        category: 'Double',
        priority: 'Medium',
        status: 'Cleaned',
      },
    ],
    expanded: true,
  },
  {
    date: 'Tuesday, Oct 24 ',
    workingHours: 'Day Off',
    breakTime: 'Time to relax and recharge!',
    tasks: [],
    expanded: false,
    isDayOff: true,
  },
  {
    date: 'Wednesday, Oct 25',
    workingHours: '9:00 AM – 5:00 PM',
    breakTime: '1:00 PM – 1:30 PM',
    tasks: [
      {
        id: 6,
        room: '9',
        task: 'Deep Cleaning',
        category: 'Deluxe',
        priority: 'High',
        status: 'Dirty',
      },
      {
        id: 7,
        room: '14',
        task: 'Standard Cleaning',
        category: 'Single',
        priority: 'Medium',
        status: 'Cleaned',
      },
      {
        id: 8,
        room: '2',
        task: 'VIP Cleaning',
        category: 'Double',
        priority: 'High',
        status: 'Inspected',
      },
    ],
    expanded: false,
  },
  {
    date: 'Thursday, Oct 26 ',
    workingHours: 'Day Off',
    breakTime: '12:00 PM – 12:30 PM',
    tasks: [
      {
        id: 12,
        room: '17',
        task: 'Standard Cleaning',
        category: 'Single',
        priority: 'Medium',
        status: 'Dirty',
      },
      {
        id: 13,
        room: '8',
        task: 'Deep Cleaning',
        category: 'Suite',
        priority: 'High',
        status: 'Dirty',
      },
    ],
    expanded: false,
    isDayOff: false,
  },
  {
    date: 'Friday, Oct 27',
    workingHours: '8:00 AM – 4:00 PM',
    breakTime: '12:00 PM – 12:30 PM',
    tasks: [
      {
        id: 12,
        room: '17',
        task: 'Standard Cleaning',
        category: 'Single',
        priority: 'Medium',
        status: 'Dirty',
      },
      {
        id: 13,
        room: '8',
        task: 'Deep Cleaning',
        category: 'Suite',
        priority: 'High',
        status: 'Dirty',
      },
    ],
    expanded: false,
  },
  {
    date: 'Saturday, Oct 28',
    workingHours: '9:00 AM – 3:00 PM',
    breakTime: '12:00 PM – 12:30 PM',
    tasks: [
      {
        id: 14,
        room: '4',
        task: 'Standard Cleaning',
        category: 'Single',
        priority: 'Medium',
        status: 'Cleaned',
      },
      {
        id: 15,
        room: '11',
        task: 'VIP Cleaning',
        category: 'Double',
        priority: 'High',
        status: 'Inspected',
      },
    ],
    expanded: false,
  },
  {
    date: 'Sunday, Oct 29',
    workingHours: '10:00 AM – 2:00 PM',
    breakTime: '12:00 PM – 12:30 PM',
    tasks: [
      {
        id: 16,
        room: '10',
        task: 'Deep Cleaning',
        category: 'Single',
        priority: 'High',
        status: 'Cleaned',
      },
      {
        id: 17,
        room: '16',
        task: 'VIP Cleaning',
        category: 'Deluxe',
        priority: 'Highest',
        status: 'Inspected',
      },
    ],
    expanded: false,
  },
];
