export const CLEANING_TASKS = [
  {
    id: '1',
    room: '101',
    category: 'Standard',
    description: 'Full cleaning including bathroom',
    dueDate: '2023-06-15T10:00:00',
    priority: 'High',
    status: 'pending',
    createDate: '2023-06-10T08:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm1',
        type: 'maintenance',
        description: 'Bathroom faucet leaking',
        status: 'open',
      },
      {
        id: 'd1',
        type: 'damage',
        description: 'Crack in wall tile',
        status: 'pending',
      },
    ],
  },
  {
    id: '2',
    room: '202',
    category: 'Deluxe',
    description: 'Change bed sheets and towels',
    dueDate: '2023-06-15T12:00:00',
    priority: 'Medium',
    status: 'pending',
    createDate: '2023-06-10T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd2',
        type: 'damage',
        description: 'Headboard scratched',
        status: 'resolved',
      },
    ],
  },
  {
    id: '3',
    room: '305',
    category: 'Suite',
    description: 'Deep cleaning after checkout',
    dueDate: '2023-06-14T14:00:00',
    priority: 'High',
    status: 'completed',
    createDate: '2023-06-09T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm3',
        type: 'maintenance',
        description: 'AC not cooling',
        status: 'in-progress',
      },
      {
        id: 'd3',
        type: 'damage',
        description: 'Mirror cracked',
        status: 'open',
      },
    ],
  },
  {
    id: '4',
    room: '107',
    category: 'Standard',
    description: 'Quick refresh between guests',
    dueDate: '2023-06-16T09:00:00',
    priority: 'Low',
    status: 'pending',
    createDate: '2023-06-11T08:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '5',
    room: '210',
    category: 'Deluxe',
    description: 'VIP guest preparation',
    dueDate: '2023-06-13T16:00:00',
    priority: 'High',
    status: 'completed',
    createDate: '2023-06-08T11:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm5',
        type: 'maintenance',
        description: 'TV remote not working',
        status: 'resolved',
      },
    ],
  },
  {
    id: '6',
    room: '115',
    category: 'Standard',
    description: 'Regular daily cleaning',
    dueDate: '2023-06-15T11:00:00',
    priority: 'Medium',
    status: 'pending',
    createDate: '2023-06-10T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '7',
    room: '301',
    category: 'Suite',
    description: 'Special request: extra towels',
    dueDate: '2023-06-14T13:00:00',
    priority: 'Medium',
    status: 'completed',
    createDate: '2023-06-09T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd7',
        type: 'damage',
        description: 'Broken wardrobe door',
        status: 'open',
      },
    ],
  },
  {
    id: '8',
    room: '204',
    category: 'Deluxe',
    description: 'Full cleaning with carpet shampoo',
    dueDate: '2023-06-16T15:00:00',
    priority: 'High',
    status: 'pending',
    createDate: '2023-06-11T10:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm8',
        type: 'maintenance',
        description: 'Clogged shower drain',
        status: 'in-progress',
      },
    ],
  },
  {
    id: '9',
    room: '102',
    category: 'Standard',
    description: 'Checkout cleaning',
    dueDate: '2023-06-14T10:00:00',
    priority: 'Medium',
    status: 'completed',
    createDate: '2023-06-09T08:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '10',
    room: '208',
    category: 'Deluxe',
    description: 'Prepare for long-term guest',
    dueDate: '2023-06-15T14:00:00',
    priority: 'High',
    status: 'pending',
    createDate: '2023-06-10T12:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'd10',
        type: 'damage',
        description: 'Window curtain torn',
        status: 'pending',
      },
    ],
  },
  {
    id: '11',
    room: '303',
    category: 'Suite',
    description: 'Full service with minibar restock',
    dueDate: '2023-06-16T11:00:00',
    priority: 'High',
    status: 'pending',
    createDate: '2023-06-11T09:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [],
  },
  {
    id: '12',
    room: '110',
    category: 'Standard',
    description: 'Quick tidy up',
    dueDate: '2023-06-15T09:00:00',
    priority: 'Low',
    status: 'Completed',
    createDate: '2023-06-10T07:00:00',
    type: 'cleaning',
    maintenanceAndDamages: [
      {
        id: 'm12',
        type: 'maintenance',
        description: 'Light bulb flickering',
        status: 'resolved',
      },
    ],
  },
];
