export const _notifications = [
  {
    id: '14',
    title: 'New Weekly Roster',
    description: 'View your assigned tasks for the week of Jan 1 – Jan 7.',
    type: 'schedule-update',
    createdAt: new Date('2024-12-26T07:00:00'),
    isUnRead: true,
  },
  {
    id: '15',
    title: 'Holiday Shift Assigned',
    description: 'You are scheduled to work on New Year’s Day.',
    type: 'schedule-update',
    createdAt: new Date('2024-12-25T12:00:00'),
    isUnRead: true,
  },
  {
    id: '1',
    title: 'New Training Available',
    description: 'Complete the "Chemical Safety" video module to improve your handling skills.',
    type: 'training',
    createdAt: new Date('2024-12-25T08:30:00'),
    isUnRead: true,
  },
  {
    id: '2',
    title: 'Item Request Approved',
    description: 'Your request for 50 Bath Towels has been approved.',
    type: 'item-request',
    createdAt: new Date('2024-12-22T10:00:00'),
    isUnRead: true,
  },
  {
    id: '3',
    title: 'Training Reminder',
    description: 'Dont forget to start the Room Inspection" interactive module.',
    type: 'training',
    createdAt: new Date('2024-12-21T09:15:00'),
    isUnRead: false,
  },
  {
    id: '16',
    title: 'Shift Reminder',
    description: 'You’re scheduled for an early shift tomorrow (6:00 AM).',
    type: 'schedule-update',
    createdAt: new Date('2024-12-21T08:30:00'),
    isUnRead: true,
  },
  {
    id: '4',
    title: 'Item Request Rejected',
    description: 'Request for 30 Light Bulbs was rejected. Please review the request.',
    type: 'item-request',
    createdAt: new Date('2024-12-20T11:45:00'),
    isUnRead: true,
  },
  {
    id: '5',
    title: 'Module Completed',
    description: 'You earned the "Certified" badge in Fire Safety Procedures.',
    type: 'training',
    createdAt: new Date('2024-12-19T13:20:00'),
    isUnRead: false,
  },
  {
    id: '6',
    title: 'New SOP Available',
    description: 'Download the updated "Waste Management SOP" document.',
    type: 'training',
    createdAt: new Date('2024-12-18T15:00:00'),
    isUnRead: true,
  },
  {
    id: '7',
    title: 'Request Received',
    description: '150 Coffee Pods have been marked as received.',
    type: 'cleaning-task',
    createdAt: new Date('2024-12-19T16:00:00'),
    isUnRead: false,
  },
  {
    id: '17',
    title: 'Friday Schedule Change',
    description: 'Break time moved from 12:30 PM to 1:00 PM.',
    type: 'schedule-update',
    createdAt: new Date('2024-12-18T10:30:00'),
    isUnRead: false,
  },
  {
    id: '8',
    title: 'Inventory Update',
    description: 'Cleaning Sprays request was approved on Dec 14.',
    type: 'cleaning-task',
    createdAt: new Date('2024-12-14T08:00:00'),
    isUnRead: true,
  },
  {
    id: '9',
    title: 'Progress Alert',
    description: 'You are 80% through the "Guest Interaction Etiquette" training.',
    type: 'training',
    createdAt: new Date('2024-12-17T17:30:00'),
    isUnRead: false,
  },
  {
    id: '10',
    title: 'Checklist Added',
    description: 'The new Deep Cleaning Checklist is available to download.',
    type: 'training',
    createdAt: new Date('2024-12-15T14:00:00'),
    isUnRead: true,
  },
  {
    id: '11',
    title: 'Schedule Updated',
    description: 'Your cleaning schedule for Monday, Oct 23 has been updated.',
    type: 'schedule-update',
    createdAt: new Date('2024-12-23T08:00:00'),
    isUnRead: true,
  },
  {
    id: '12',
    title: 'Shift Change',
    description: 'Your Wednesday shift has been moved from 9am to 10am.',
    type: 'schedule-update',
    createdAt: new Date('2024-12-22T14:30:00'),
    isUnRead: true,
  },
  {
    id: '13',
    title: 'Weekend Schedule',
    description: 'You have been assigned to the weekend cleaning rotation.',
    type: 'schedule-update',
    createdAt: new Date('2024-12-21T16:45:00'),
    isUnRead: false,
  },
  {
    id: '18',
    title: 'Coverage Needed',
    description: 'Can you cover the Tuesday evening shift?',
    type: 'schedule-update',
    createdAt: new Date('2024-12-13T11:15:00'),
    isUnRead: true,
  },
];
